name: Hank Quinlan, Horrible Cop
markdown: kramdown
collections:
  documentation:
    output: true
  hobbies:
    output: true
url: "https://psoltes.github.io/" # the base hostname & protocol for your site
plugins:
  - jekyll-sitemap
  - jemoji